# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Love Hair by Charmaine
email: dbmorris@hotmail.co.uk
description: Love hair is a cruelty free, vegan friendly hairdressers in Urmston, Manchester. We offer luxury hair care and guilt free pampering in a relaxing environment. Trained in Andrew Collinge with over 10 years experience.
baseurl: "/love-hair-by-charmaine"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: monotonemorris
github_username:  dave-morris

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /img/love-hair-logo-default.png

social:
  name: Love Hair by Charmaine
  links:
  - https://twitter.com/LoveHairUrmston
  - https://www.facebook.com/lovehairbycharmaine/
  - https://www.instagram.com/lovehairbycharmaine/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
