backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)

media_folder: "img" # Media files will be stored in the repo under images/uploads

site_url: https://lovehairbycharmaine.co.uk
logo_url: https://lovehairbycharmaine.co.uk/img/love-hair-logo-3.png

collections:
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/test.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }
  - name: "opening-times"
    label: "Opening Times"
    editor:
      preview: false
    files:
      - label: "Change your opening times"
        name: "Opening Hours"
        file: "_data/opening-hours.yml"
        fields:
          - label: "Salon opening times"
            name: "days"
            delete: false
            widget: "list"
            fields:
              - { label: Salon closed this day?, name: closed, widget: boolean }
              - { label: Salon opens, name: open, widget: string, required: false }
              - { label: Salon closes, name: close, widget: string, required: false }
              - { label: Other information, name: message, widget: string, required: false }


              