backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)

media_folder: "img" # Media files will be stored in the repo under images/uploads

site_url: https://lovehairbycharmaine.co.uk
logo_url: https://lovehairbycharmaine.co.uk/img/love-hair-logo-3.png

collections:
  - label: "Salon details"
    name: "details"
    description: Update opening times and various information about the salon
    files: 
    - label: "Opening times"
      name: "opening_times"
      file: "includes/opening-hours.html"
      extensions: html
      fields:
        - {label: Title, name: title, widget: string }
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/test.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }
  - name: "opening-times"
    label: "Opening Times"
    editor:
      preview: false
    files:
      - label: "Change your opening times"
        name: "Opening Hours"
        file: "_data/opening-hours.yml"
        fields:
          - label: "Salon opening times"
            name: "days"
            widget: "list"
            fields:
              - { label: closed?, name: closed, widget: boolean }
              - { label: opens, name: open, widget: string }
              - { label: closes, name: close, widget: string }
              - { label: additional message, name: message, widget: string }


              