backend:
  name: git-gateway
  branch: gh-pages # Branch to update (optional; defaults to master)

media_folder: "img" # Media files will be stored in the repo under images/uploads

site_url: https://lovehairbycharmaine.co.uk
logo_url: https://lovehairbycharmaine.co.uk/img/love-hair-logo-3.png

collections:
  - label: "Salon details"
    name: "details"
    description: Update opening times and various information about the salon
    files: 
    - label: "Opening times"
      name: "opening_times"
      file: "site/includes/opening-hours.html"
      extensions: html
      fields:
        - {label: Title, name: title, widget: string }
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
      - label: 'Navigation'
        name: 'navigation'
        file: '_data/test.yml'
        fields:
          - label: 'Navigation Items'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }