backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)

media_folder: "img" # Media files will be stored in the repo under images/uploads

site_url: https://lovehairbycharmaine.co.uk
logo_url: https://lovehairbycharmaine.co.uk/img/love-hair-logo-3.png

collections:
- label: "Opening times"
  name: "opening-times"
  editor:
    preview: false
  files:
    - label: "Change your opening times"
      name: "change-opening-times"
      file: "_data/opening-hours.yml"
      fields:
        - label: 'Opening times'
          name: 'days'
          summary: '{{ name }}'
          widget: list
          fields:
            - {label: Is the salon closed?, name: closed, widget: boolean, required: true}
            - {label: Salon opens, name: open, widget: string, required: false}
            - {label: Salon closes, name: close, widget: string, required: false} 
            - {label: Additional info, name: message, widget: string, required: false}
- label: "price-list"
  name: "Price list"
  editor:
    preview: false
  files:
    - label: "Main services"
      name: "main-services"
      file: "_data/main-services.json"
      fields: 
        - {name: title}
    - label: "High & Low Lighting"
      name: "high-low-lighting"
      file: "_data/highlowlighting.json"
      fields: 
        - label: "High & Lowlighting Treatments"
          name: "services"
          widget: list
          summary: "{{ services.title }}"
          fields:
            - {label: Price, name: price, widget: string, required: true}
    - label: "Balayage"
      name: "balayage"
      file: "_data/balayage.json"
      fields:
        - label: "Treatments"
          name: "services"
          widget: list
          summary: "{{ title }}"
          fields: 
            - {label: Name of treatment, name: title, widget: string, required: true}
            - {label: Price, name: price, widget: string, required: true}